### ISSUE TITLE
Thought about static generation?

### ISSUE THREAD

**Issue by hongkongkiwi** [kirankunigiri/zenstack-ui#1]
Thanks for this, it's great work. I'm really looking forward to seeing some of the features on the feature list implemented. This is exactly what I was looking for.

I'm curious though, what made you come up with dynamic forms rather than statically generating them (like how Zenstack generates the prisma schema).

Did you consider static generation?

**Comment by kirankunigiri** [comment]
Thanks for checking this out! I actually just pushed a huge new update today that I think will explain why I went with dynamic forms.

I actually originally was thinking of static generation, but a major problem I realized is that it would lead to a lack of customization. Even the original version of zenstack-ui I created did not have many customization options, and after trying to use it in my own project, the lack of customization made it useless in my project. I needed forms that would sometimes omit specific fields, or replace zenstack hooks for server-side hooks for specific models. Many other forms required complete UI customization with custom elements and styling that was beyond just a simple vertical list of fields.

The new update I pushed today allows all of those things to be done, but it's only possible with dynamic form creation. I introduced a new feature with form templating, where you can pass in custom elements or simple div's that the form will automatically replace with it's own elements. Ex: create a custom styled template that looks however you want, mark specific div's with field id's, and the form will replace and inject it's own custom fields. It makes using forms a breeze now and I was finally able to use it in my own projects. 

Along with this comes a bunch of new features (filtering, field dependencies, schema overrides, etc.), feel free to check out the docs (which I just updated today) and the example project which has also been updated and is a good example of how to use this. Also feel free to contact me in the zenstack discord! I am active there as well. Would love to continue this discussion and get feedback on this project.
