### ISSUE TITLE
Many different types for String field

### ISSUE THREAD

**Issue by hongkongkiwi** [kirankunigiri/zenstack-ui#3]
this seems to work....
  [FieldType.String]: (props) => {
    // Check if this is the company license field
    if (props['data-path'] === 'companyLicenseNumber') {
      return <FormInput 
        {...props} 
        className="uppercase"
        maxLength={20}
        placeholder="Enter company license number"
      />;
    }
    // Otherwise use the default FormInput
    return <FormInput {...props} />;
  },

but is there a better way? I have many different types I want to use but the underlying type is String.

For example:
- Country Selector
- Auto Complete Google Selector
etc

The alternative I came up with is to define a json type in postgres and then it shows up as a type. But for some fields that's a bit clunky.

I'm just wondering how this should be done?

**Comment by kirankunigiri** [comment]
I think the easiest way is to just modify the metadata object before setting your zenstack-ui config object. You can set the field to use a custom type, and then set that type to a custom element in the element map.

Define the name of your new type (or even create a new custom type enum for organizing multiple custom fields).
```ts
const MyCustomType = 'MyCustomType';
meta.models.item.fields.category.type = MyCustomType; // set the fields you want to the new type
```

Then update the element map.
```ts
const mapFieldTypeToElement: MapFieldTypeToElement = {
	[FieldType.Boolean]: Checkbox,
	//... other default types

	// Example of adding custom types
	[MyCustomType]: () => <div>My Custom Type Element</div>,
};
```

Check the [example form config file](https://github.com/kirankunigiri/zenstack-ui/blob/main/example-client/src/form/form-config.tsx) as well for more customization details. Let me know if this works for you.

**Comment by hongkongkiwi** [comment]
Ah thanks for the example about setting a custom type, that's really helpful. I like it better than my method.

Currently I managed to do that with a json field and setting the schema to that type. Which I guess then populated the type with the correct string. But I like your way better.

This is how I was currently doing it:
```
type GooglePlacesAutocomplete {
  placeId String?
  formattedAddress String?
  latitude Float?
  longitude Float?
  streetNumber String?
  route String?
  locality String?
  administrativeAreaLevel1 String?
  administrativeAreaLevel2 String?
  country String?
  postalCode String?
}

model Place {
  address GooglePlacesAutocomplete @json
}
```

Then in my code i could deal with it like this:
```
export const mapFieldTypeToElement: MapFieldTypeToElement = {
  GooglePlacesAutocomplete: (props) => <FormAddressInput {...props} />
}
```
