### ISSUE TITLE
Will users without "read" permission see items in the listing type?

### ISSUE THREAD

**Issue by hongkongkiwi** [kirankunigiri/zenstack-ui#5]
How does the list type work with permissions? Does it currently exclude items from the list if user doesn't have permission to read them?

I guess this is kind of related to https://github.com/zenstackhq/zenstack/issues/982 but seems not exactly since we only want to see some items in the list if user has permissions to "read".

**Comment by kirankunigiri** [comment]
This project uses zenstack's [tanstack-query](https://zenstack.dev/docs/reference/plugins/tanstack-query) plugin under the hood, so I believe it should respect all access policies and other zenstack features by default. For the list, it specifically is using the `useFindMany` hook that zenstack creates, check the docs I linked for more details. I haven't tested the list component with permissions myself though, so let me know if it works for you.

**Comment by hongkongkiwi** [comment]
Thanks, makes sense.
